/* スマホ用ホーム：大きなタイルから必要な機能を選ぶアプリ型メニュー */
(function(){
  'use strict';
  const $=s=>document.querySelector(s);
  function style(){const s=document.createElement('style');s.textContent=`
    .app-home{display:none}.app-nav{display:flex;position:fixed;z-index:1000;left:0;right:0;bottom:0;height:72px;padding:7px 12px;background:rgba(255,255,255,.97);border-top:1px solid #d8e0e8;box-shadow:0 -4px 16px rgba(33,60,88,.1);justify-content:center}.app-nav button,.app-nav a{min-height:54px;max-width:150px;flex:1 1 120px;padding:3px 2px;border:0;background:transparent;color:#73839a;font-size:11px;line-height:1.25;text-decoration:none;text-align:center}.app-nav button b,.app-nav a b{display:block;font-size:21px;font-weight:500;line-height:25px}.app-nav button.on,.app-nav a.on{color:#20ace4}.app-nav button.on b,.app-nav a.on b{font-weight:750}body{padding-bottom:88px!important}
    :root{--bg:#fff6fa;--card:#fff;--line:#f0dce5;--txt:#513d49;--sub:#8c7180;--pre:#d8789f;--trip:#df9b77;--ok:#6f9d86;--ng:#c76b7d;--warn:#d59b48}body{background:#fff6fa!important}.wrap>.card:first-of-type{background:linear-gradient(135deg,#d985a6,#edb3c7)!important;box-shadow:0 8px 24px rgba(194,100,141,.18)!important}.wrap>.card:first-of-type #newTrip{color:#a64f74!important}.tabs button.on{color:#a64f74!important}.app-nav button.on,.app-home-close,.app-home-trip{color:#d76d98!important}.app-home{background:#fff8fb!important}.app-home-tile{border-color:#f0cfdd!important;color:#d76d98!important}.app-home-tile:active{background:#fff0f5!important}.top a{color:#d76d98!important}.trip{background:linear-gradient(130deg,#d985a6,#edb3c7)!important}.events{border-color:#f1c9d9!important}.event:before,.progress i{background:#d76d98!important}.add{border-color:#edb8ce!important;background:#fff7fa!important;color:#c85f8b!important}.choice button{border-color:#f0cddd!important;background:#fff7fa!important;color:#c85f8b!important}.choice button.on{background:#d76d98!important;border-color:#d76d98!important;color:#fff!important}.flight-ticket{border-color:#efc5d5!important;border-left-color:#d76d98!important;background:linear-gradient(110deg,#fff7fa,#fff)!important}.flight-route{background:#fff5f9!important}.flight-dot{fill:#d76d98!important}.split-members span{background:#fff0f5!important;color:#b34f78!important}.split-settlements{background:#fff1f6!important}.split-settlements strong,.plus{color:#9d5572!important}
    /* 色数を抑えた、白・グレー・淡いローズ1色のテーマ */
    :root{--bg:#faf9fa;--card:#fff;--line:#e9e4e6;--txt:#363136;--sub:#7d7479;--pre:#c98299;--trip:#c98299;--ok:#70887a;--ng:#b56c78;--warn:#aa8554}body{background:#faf9fa!important}.wrap>.card:first-of-type,.trip{background:#fff!important;color:#363136!important;box-shadow:none!important;border:1px solid #e9e4e6!important}.wrap>.card:first-of-type .muted,.wrap>.card:first-of-type label{color:#7d7479!important}.wrap>.card:first-of-type button{background:#fff!important;color:#363136!important;border-color:#e9e4e6!important}.wrap>.card:first-of-type #newTrip{background:#c98299!important;color:#fff!important;border-color:#c98299!important}.app-nav{background:#fff!important;border-color:#e9e4e6!important;box-shadow:0 -2px 10px rgba(40,30,35,.05)!important}.app-nav button.on,.app-home-close,.app-home-trip{color:#b56c82!important}.app-home{background:#faf9fa!important}.app-home-tile{border-color:#e9e4e6!important;color:#363136!important;box-shadow:none!important}.app-home-tile i{color:#c98299!important}.app-home-tile:active{background:#fff4f7!important}.top a{color:#b56c82!important}.events{border-color:#ead8de!important}.event:before,.progress i{background:#c98299!important}.add{border-color:#e9e4e6!important;background:#fff!important;color:#6c5962!important}.choice button{border-color:#e9e4e6!important;background:#fff!important;color:#5d5157!important}.choice button.on{background:#c98299!important;border-color:#c98299!important;color:#fff!important}.flight-ticket{border-color:#e9e4e6!important;border-left-color:#c98299!important;background:#fff!important}.flight-route{background:#faf9fa!important}.flight-dot{fill:#c98299!important}.split-members span{background:#f8f1f3!important;color:#795966!important}.split-settlements{background:#faf6f7!important}.split-settlements strong,.plus{color:#6e806f!important}
    /* 一般的な白・グレー・青1色の配色。割り勘ページは割り勘だけを表示する。 */
    :root{--bg:#f7f8fa;--card:#fff;--line:#e3e7ed;--txt:#252b33;--sub:#6b7785;--pre:#2563eb;--trip:#2563eb;--ok:#268a62;--ng:#c34d5b;--warn:#b7791f}body{background:#f7f8fa!important}.wrap>.card:first-of-type,.trip{background:#fff!important;color:#252b33!important;border-color:#e3e7ed!important}.wrap>.card:first-of-type #newTrip{background:#2563eb!important;border-color:#2563eb!important}.app-nav button.on,.app-home-close,.app-home-trip{color:#2563eb!important}.app-home-tile i{color:#2563eb!important}.app-home-tile:active{background:#f3f7ff!important}.top a{color:#2563eb!important}.event:before,.progress i{background:#2563eb!important}.add{color:#2563eb!important}.choice button{color:#2563eb!important}.choice button.on{background:#2563eb!important;border-color:#2563eb!important}.flight-ticket{border-left-color:#2563eb!important}.flight-dot{fill:#2563eb!important}.page-tools .flight-tabs{display:none!important}.page-tools #flightTools>h3{display:none!important}
    @media(max-width:900px){
      body{padding-bottom:88px!important}.app-nav{display:flex;position:fixed;z-index:1000;left:0;right:0;bottom:0;height:72px;padding:7px max(12px,env(safe-area-inset-left)) calc(7px + env(safe-area-inset-bottom)) max(12px,env(safe-area-inset-right));background:rgba(255,255,255,.97);border-top:1px solid #d8e0e8;box-shadow:0 -4px 16px rgba(33,60,88,.1);justify-content:space-around}.app-nav button{min-height:54px;flex:1 1 25%;padding:3px 2px;border:0;background:transparent;color:#73839a;font-size:11px;line-height:1.25}.app-nav button b{display:block;font-size:21px;font-weight:500;line-height:25px}.app-nav button.on{color:#20ace4}.app-nav button.on b{font-weight:750}
      .app-home.open{display:block;position:fixed;z-index:1500;inset:0;overflow-y:auto;background:#f7f8fa;padding-bottom:28px}.app-home-head{height:112px;display:grid;grid-template-columns:70px 1fr 92px;align-items:center;padding:env(safe-area-inset-top) 18px 0;background:#fff;border-bottom:1px solid #d5d9dd;box-shadow:0 2px 7px rgba(0,0,0,.08)}.app-home-head h2{margin:0;text-align:center;font-size:26px;color:#4a4a4a;letter-spacing:.05em}.app-home-close{width:48px;height:48px;border-radius:24px;border:1px solid #e2e5e8;background:#fff;color:#20ace4;font-size:26px}.app-home-trip{min-height:48px;border-radius:25px;border:1px solid #e5e8eb;background:#fff;color:#20ace4;font-size:15px;white-space:nowrap}.app-home-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px;padding:28px 24px}.app-home-tile{aspect-ratio:1/1;min-height:174px;padding:16px 8px;border:2px solid #d0d2d4;border-radius:10px;background:#fff;color:#24afe8;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;box-shadow:0 1px 2px rgba(0,0,0,.03)}.app-home-tile i{font-style:normal;font-size:48px;line-height:1;margin-bottom:18px}.app-home-tile strong{font-size:22px;font-weight:500;line-height:1.25}.app-home-tile span{display:block;margin-top:14px;color:#999;font-size:13px;line-height:1.35}.app-home-tile:active{transform:scale(.98);background:#f4fbff}.hasbar .app-nav{bottom:102px}body.hasbar{padding-bottom:200px!important}
    }`;document.head.appendChild(s);}
  function detail(){const list=$('#viewList');if(list&&!list.hidden)$('#toList')?.click();}
  function jump(sel,tab){detail();setTimeout(()=>{if(tab)document.querySelector(tab)?.click();$(sel)?.scrollIntoView({behavior:'smooth',block:'start'});},40);}
  function nav(){
    if($('.app-nav'))return;
    const n=document.createElement('nav');n.className='app-nav';n.setAttribute('aria-label','アプリメニュー');n.innerHTML='<a data-go="trip" href="./itinerary.html"><b>▤</b>旅程</a><a data-go="budget" href="./index.html?page=budget"><b>¥</b>予算</a><a data-go="rates" href="./index.html?page=rates"><b>⇄</b>為替</a><a data-go="flight" href="./index.html?page=flights"><b>✈</b>航空券</a><a data-go="tools" href="./index.html?page=tools"><b>÷</b>割勘</a><a data-go="packing" href="./packing.html"><b>☑</b>持物</a><a data-go="settings" href="./index.html?page=settings"><b>⚙</b>設定</a><button data-go="menu" class="on"><b>☰</b>ホーム</button>';
    const home=document.createElement('main');home.className='app-home';home.setAttribute('aria-label','ホームメニュー');home.innerHTML='<header class="app-home-head"><button class="app-home-close" aria-label="閉じる">×</button><h2>ホーム</h2><button class="app-home-trip">旅行予算⌄</button></header><section class="app-home-grid"><button class="app-home-tile" data-home="budget"><i>￥</i><strong>予算・精算</strong><span>旅行前・旅行中の支出</span></button><button class="app-home-tile" data-home="flight"><i>✈</i><strong>航空券</strong><span>予約・運航情報</span></button><button class="app-home-tile" data-home="list"><i>▤</i><strong>旅程</strong><span>日ごとの予定</span></button><button class="app-home-tile" data-home="rates"><i>⇄</i><strong>為替</strong><span>通貨・レート換算</span></button><button class="app-home-tile" data-home="tools"><i>÷</i><strong>割り勘</strong><span>支払い・精算結果</span></button><button class="app-home-tile" data-home="packing"><i>☑</i><strong>持ち物</strong><span>国内・海外の準備</span></button><button class="app-home-tile" data-home="settings"><i>⚙</i><strong>設定</strong><span>日程・予算・基準通貨</span></button></section>';
    document.body.append(n,home);const active=x=>n.querySelectorAll('[data-go]').forEach(b=>b.classList.toggle('on',b.dataset.go===x));const open=()=>{home.classList.add('open');active('menu');},close=()=>home.classList.remove('open');
    function go(x){if(x==='trip'||x==='list'){location.href='./itinerary.html';return;}if(x==='packing'){location.href='./packing.html';return;}if(x==='budget'){location.href='./index.html?page=budget';return;}if(x==='settings'){location.href='./index.html?page=settings';return;}if(x==='flight'){location.href='./index.html?page=flights';return;}if(x==='rates'){location.href='./index.html?page=rates';return;}if(x==='tools'){location.href='./index.html?page=tools';return;}close();}
    n.onclick=e=>{const b=e.target.closest('[data-go]');if(!b)return;const x=b.dataset.go;if(x==='menu')open();else{active(x);go(x);}};home.onclick=e=>{if(e.target.closest('.app-home-close'))close();const b=e.target.closest('[data-home]');if(b)go(b.dataset.home);};const dedicated=new URLSearchParams(location.search).has('page')||/(itinerary|packing)\.html$/.test(location.pathname);if(matchMedia('(max-width:900px)').matches&&!dedicated)setTimeout(open,0);
  }
  style();nav();new MutationObserver(nav).observe(document.body,{childList:true});if(/packing\.html$/.test(location.pathname)){const s=document.createElement('script');s.src='./packing-custom.js';document.body.appendChild(s);const o=document.createElement('script');o.src='./packing-optional.js';document.body.appendChild(o);}
})();
