(()=>{
  'use strict';
  const K='travelBudget.v3',$=s=>document.querySelector(s),uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
  const esc=s=>String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  let db; const load=()=>{try{return JSON.parse(localStorage.getItem(K))}catch(e){return null}},save=()=>localStorage.setItem(K,JSON.stringify(db)),trip=()=>db.trips.find(t=>t.id===db.activeId)||db.trips[0];
  function dates(t){if(!t.start)return [];const end=t.end&&t.end>=t.start?t.end:t.start,a=[],d=new Date(t.start+'T00:00:00'),z=new Date(end+'T00:00:00');for(;d<=z;d.setDate(d.getDate()+1))a.push(d.toISOString().slice(0,10));return a}
  function open(ev,date){$('#form').reset();$('#eventId').value=ev?.id||'';$('#formTitle').textContent=ev?'予定を編集':'予定を追加';$('#date').value=ev?.date||date||new Date().toISOString().slice(0,10);$('#time').value=ev?.time||'';$('#title').value=ev?.title||'';$('#place').value=ev?.place||'';$('#memo').value=ev?.memo||'';$('#sheet').classList.add('open')}
  function render(){const t=trip();t.itinerary=Array.isArray(t.itinerary)?t.itinerary:[];$('#tripSel').innerHTML=db.trips.map(x=>'<option value="'+x.id+'">'+esc(x.name||'名称未設定')+'</option>').join('');$('#tripSel').value=t.id;const all=Array.from(new Set(dates(t).concat(t.itinerary.map(x=>x.date).filter(Boolean)))).sort();$('#days').innerHTML=all.length?all.map((d,i)=>{const es=t.itinerary.filter(x=>x.date===d).sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99')),label='DAY '+(i+1)+'　'+new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'short'}).format(new Date(d+'T00:00:00'));return '<section class="day"><div class="dayhead"><b>'+label+'</b><span>'+d+'</span></div><div class="events">'+(es.map(e=>'<article class="event"><div class="event-row"><span class="time">'+esc(e.time||'終日')+'</span><span class="title">'+esc(e.title)+'</span><button class="del" data-del="'+e.id+'" aria-label="削除">×</button></div>'+(e.place?'<div class="place">⌖ '+esc(e.place)+'</div>':'')+(e.memo?'<div class="memo">'+esc(e.memo)+'</div>':'')+'</article>').join('')||'<p class="empty">予定はまだありません</p>')+'<button class="add" data-add="'+d+'">＋ この日に予定を追加</button></div></section>'}).join(''):'<p class="empty">ホームの「設定」から旅行期間を登録すると、日ごとのページを自動作成できます。<br><button class="add" id="freeAdd">＋ 予定を追加</button></p>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>open(null,b.dataset.add));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('この予定を削除しますか？')){t.itinerary=t.itinerary.filter(x=>x.id!==b.dataset.del);save();render()}});$('#freeAdd')?.addEventListener('click',()=>open())}
  db=load();if(!db?.trips?.length){document.querySelector('.wrap').innerHTML='<p class="empty">旅行データがありません。先にホームで旅程を作成してください。</p>';return}render();
  $('#tripSel').onchange=e=>{db.activeId=e.target.value;save();render()};$('#cancel').onclick=()=>$('#sheet').classList.remove('open');$('#sheet').onclick=e=>{if(e.target===$('#sheet'))$('#sheet').classList.remove('open')};
  $('#form').onsubmit=e=>{e.preventDefault();const t=trip(),id=$('#eventId').value;t.itinerary=Array.isArray(t.itinerary)?t.itinerary:[];const v={id:id||uid(),date:$('#date').value,time:$('#time').value,title:$('#title').value.trim(),place:$('#place').value.trim(),memo:$('#memo').value.trim()};if(id)t.itinerary[t.itinerary.findIndex(x=>x.id===id)]=v;else t.itinerary.push(v);save();$('#sheet').classList.remove('open');render()};
  window.addEventListener('storage',e=>{if(e.key===K){db=load();render()}});
  const menu=document.createElement('script');menu.src='./app-menu.js';document.body.appendChild(menu);
})();
