(()=>{
  'use strict';
  const $=s=>document.querySelector(s),uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
  const esc=s=>String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const active=()=>new URLSearchParams(location.search).get('page')==='tools';
  function data(){const t=trip();if(!t.split)t.split={members:[],items:[]};return t}
  function calc(s){const b={};s.members.forEach(m=>b[m.id]={name:m.name,paid:0,share:0});s.items.forEach(x=>{if(!b[x.payer])return;const who=(x.members||[]).filter(v=>b[v]);b[x.payer].paid+=+x.amount||0;who.forEach(v=>b[v].share+=(+x.amount||0)/Math.max(1,who.length))});const debt=[],credit=[],moves=[];Object.entries(b).forEach(([id,v])=>{const d=v.paid-v.share;if(d>.01)credit.push([id,d]);if(d<-.01)debt.push([id,-d])});let i=0,j=0;while(i<debt.length&&j<credit.length){const n=Math.min(debt[i][1],credit[j][1]);moves.push([debt[i][0],credit[j][0],n]);debt[i][1]-=n;credit[j][1]-=n;if(debt[i][1]<.01)i++;if(credit[j][1]<.01)j++}return {b,moves}}
  function render(){if(!active())return;const root=$('#flightBody'),tab=$('[data-ft="tools"]');if(!root||root.dataset.split||!tab?.classList.contains('on'))return;root.dataset.split='1';const t=data(),s=t.split,c=calc(s),cur=t.base||'JPY';const memberTags=s.members.map(m=>'<span>'+esc(m.name)+' <button data-member="'+m.id+'">×</button></span>').join('');const opts=s.members.map(m=>'<option value="'+m.id+'">'+esc(m.name)+'</option>').join('');const checks=s.members.map(m=>'<label><input type="checkbox" value="'+m.id+'" checked>'+esc(m.name)+'</label>').join('');const pays=s.items.map(x=>'<div><b>'+esc(x.name||'支払い')+'</b><small>'+Number(x.amount||0).toLocaleString()+' '+cur+' ／ '+esc(c.b[x.payer]?.name||'')+'が支払い</small><button data-item="'+x.id+'">削除</button></div>').join('');const balances=s.members.map(m=>{const v=c.b[m.id],n=v.paid-v.share;return '<div><b>'+esc(m.name)+'</b><small>支払 '+v.paid.toLocaleString()+' ／ 負担 '+v.share.toLocaleString()+'</small><strong class="'+(n>=0?'plus':'minus')+'">'+(n>=0?'受取 ':'支払 ')+Math.abs(n).toLocaleString()+' '+cur+'</strong></div>'}).join('');const moves=c.moves.map(x=>'<p><b>'+esc(c.b[x[0]].name)+'</b> → <b>'+esc(c.b[x[1]].name)+'</b><strong>'+x[2].toLocaleString(undefined,{maximumFractionDigits:0})+' '+cur+'</strong></p>').join('');root.innerHTML='<section class="split-tool"><p class="split-lead">誰が払ったかを記録すると、最後に必要な送金だけを表示します。</p><div class="split-card"><h4>参加者</h4><div class="split-members">'+(memberTags||'<em>参加者を追加してください</em>')+'</div><div class="row"><input id="spName" placeholder="例：ゆりの"><button id="spAddMember">追加</button></div></div>'+(s.members.length?'<div class="split-card"><h4>支払いを追加</h4><div class="split-fields"><label>内容<input id="spTitle" placeholder="例：ホテル代"></label><label>金額（'+cur+'）<input id="spAmount" type="number" min="0" placeholder="0"></label><label>支払った人<select id="spPayer">'+opts+'</select></label></div><p class="split-note">対象者（未選択の場合は全員）</p><div id="spWho" class="split-checks">'+checks+'</div><button id="spAddPay">この支払いを追加</button></div><div class="split-card"><h4>支払い一覧</h4><div class="split-payments">'+(pays||'<em>支払いはまだありません</em>')+'</div></div><div class="split-card"><h4>精算結果</h4><div class="split-balance">'+balances+'</div><div class="split-settlements">'+(moves||'<p>精算は不要です。</p>')+'</div></div>':'<div class="split-card"><h4>まず参加者を追加してください</h4></div>')+'</section>';bind(t)}
  function refresh(){const r=$('#flightBody');if(r)delete r.dataset.split;render()}
  function bind(t){const s=t.split,save=()=>{saveDb();refresh()};$('#spAddMember')?.addEventListener('click',()=>{const e=$('#spName'),n=e.value.trim();if(n&&!s.members.some(x=>x.name===n)){s.members.push({id:uid(),name:n});save()}});document.querySelectorAll('[data-member]').forEach(b=>b.onclick=()=>{const id=b.dataset.member;if(s.items.some(x=>x.payer===id)){alert('この参加者の支払いを先に削除してください。');return}s.members=s.members.filter(x=>x.id!==id);save()});$('#spAddPay')?.addEventListener('click',()=>{const amount=+$('#spAmount').value||0;if(!amount){alert('金額を入力してください。');return}const who=[...document.querySelectorAll('#spWho input:checked')].map(x=>x.value);s.items.push({id:uid(),name:$('#spTitle').value.trim()||'支払い',amount,payer:$('#spPayer').value,members:who.length?who:s.members.map(x=>x.id)});save()});document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{s.items=s.items.filter(x=>x.id!==b.dataset.item);save()})}
  const style=document.createElement('style');style.textContent=`.split-tool{max-width:680px}.split-lead,.split-note,.split-card em{color:#708096;font-size:13px}.split-card{margin:12px 0;padding:14px;border:1px solid #dce6f0;border-radius:14px;background:#fff}.split-card h4{margin:0 0 10px}.split-members,.split-checks{display:flex;gap:7px;flex-wrap:wrap;margin:7px 0 10px}.split-members span{padding:4px 8px;border-radius:99px;background:#eaf7fd;color:#167ca8}.split-members button,.split-payments button{border:0;background:transparent;color:#c64343}.split-fields{display:grid;grid-template-columns:2fr 1fr 1fr;gap:8px}.split-checks label{display:inline-flex;align-items:center;gap:3px}.split-checks input{width:auto}.split-payments>div,.split-balance>div{display:grid;grid-template-columns:1fr auto auto;gap:8px;padding:9px 0;border-bottom:1px solid #edf1f5}.split-payments small,.split-balance small{color:#708096}.plus{color:#168b62}.minus{color:#c64343}.split-settlements{margin-top:12px;background:#f0f9fd;border-radius:10px;padding:5px 12px}.split-settlements p{display:flex;justify-content:space-between;gap:8px}@media(max-width:600px){.split-fields{grid-template-columns:1fr}.split-payments>div,.split-balance>div{grid-template-columns:1fr auto}.split-payments button,.split-balance strong{grid-column:2}.split-settlements p{display:block}.split-settlements strong{display:block}}`;document.head.append(style);
  new MutationObserver(render).observe(document.body,{childList:true,subtree:true});setTimeout(render,180);
})();
